<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // Check if data already exists
        $studentCount = DB::table('students')->count();
        if ($studentCount > 0) {
            $this->command->info('Database already has data, skipping seed');
            return;
        }

        // Seed students
        DB::table('students')->insert([
            [
                'id' => 'ST001',
                'first_name' => 'John',
                'last_name' => 'Smith',
                'email' => 'john.smith@school.edu',
                'phone' => '+1 234-567-8900',
                'grade' => 'Grade 10',
                'status' => 'Active',
                'enrollment_date' => '2023-09-01',
                'date_of_birth' => '2008-05-15',
                'address' => '123 Main Street, New York, NY 10001',
                'parent_name' => 'Jane Smith',
                'parent_email' => 'jane.smith@email.com',
                'parent_phone' => '+1 234-567-8901',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'ST002',
                'first_name' => 'Emily',
                'last_name' => 'Johnson',
                'email' => 'emily.j@school.edu',
                'phone' => '+1 234-567-8901',
                'grade' => 'Grade 11',
                'status' => 'Active',
                'enrollment_date' => '2023-09-01',
                'date_of_birth' => '2007-03-20',
                'address' => '456 Oak Avenue, New York, NY 10002',
                'parent_name' => 'Robert Johnson',
                'parent_email' => 'robert.j@email.com',
                'parent_phone' => '+1 234-567-8902',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'ST003',
                'first_name' => 'Michael',
                'last_name' => 'Brown',
                'email' => 'michael.b@school.edu',
                'phone' => '+1 234-567-8902',
                'grade' => 'Grade 9',
                'status' => 'Active',
                'enrollment_date' => '2023-09-01',
                'date_of_birth' => '2009-07-10',
                'address' => '789 Pine Road, New York, NY 10003',
                'parent_name' => 'Sarah Brown',
                'parent_email' => 'sarah.b@email.com',
                'parent_phone' => '+1 234-567-8903',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'ST004',
                'first_name' => 'Sarah',
                'last_name' => 'Davis',
                'email' => 'sarah.d@school.edu',
                'phone' => '+1 234-567-8903',
                'grade' => 'Grade 12',
                'status' => 'Active',
                'enrollment_date' => '2022-09-01',
                'date_of_birth' => '2006-11-25',
                'address' => '321 Elm Street, New York, NY 10004',
                'parent_name' => 'David Davis',
                'parent_email' => 'david.d@email.com',
                'parent_phone' => '+1 234-567-8904',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'ST005',
                'first_name' => 'David',
                'last_name' => 'Wilson',
                'email' => 'david.w@school.edu',
                'phone' => '+1 234-567-8904',
                'grade' => 'Grade 10',
                'status' => 'Inactive',
                'enrollment_date' => '2023-09-01',
                'date_of_birth' => '2008-02-14',
                'address' => '654 Maple Drive, New York, NY 10005',
                'parent_name' => 'Lisa Wilson',
                'parent_email' => 'lisa.w@email.com',
                'parent_phone' => '+1 234-567-8905',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'ST006',
                'first_name' => 'Jessica',
                'last_name' => 'Martinez',
                'email' => 'jessica.m@school.edu',
                'phone' => '+1 234-567-8905',
                'grade' => 'Grade 11',
                'status' => 'Active',
                'enrollment_date' => '2023-09-01',
                'date_of_birth' => '2007-09-30',
                'address' => '987 Cedar Lane, New York, NY 10006',
                'parent_name' => 'Carlos Martinez',
                'parent_email' => 'carlos.m@email.com',
                'parent_phone' => '+1 234-567-8906',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Seed teachers
        DB::table('teachers')->insert([
            [
                'id' => 'TC001',
                'first_name' => 'Robert',
                'last_name' => 'Anderson',
                'email' => 'robert.a@school.edu',
                'phone' => '+1 234-567-9000',
                'subject' => 'Mathematics',
                'status' => 'Active',
                'join_date' => '2020-01-15',
                'date_of_birth' => '1980-03-20',
                'address' => '456 Faculty Lane, New York, NY 10002',
                'education' => 'Ph.D. in Mathematics, Harvard University',
                'experience' => '15 years',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'TC002',
                'first_name' => 'Maria',
                'last_name' => 'Garcia',
                'email' => 'maria.g@school.edu',
                'phone' => '+1 234-567-9001',
                'subject' => 'Science',
                'status' => 'Active',
                'join_date' => '2019-08-20',
                'date_of_birth' => '1978-06-15',
                'address' => '789 Teacher Street, New York, NY 10003',
                'education' => 'Ph.D. in Physics, MIT',
                'experience' => '18 years',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'TC003',
                'first_name' => 'Jennifer',
                'last_name' => 'Lee',
                'email' => 'jennifer.l@school.edu',
                'phone' => '+1 234-567-9002',
                'subject' => 'English',
                'status' => 'Active',
                'join_date' => '2021-03-10',
                'date_of_birth' => '1985-09-05',
                'address' => '321 Educator Avenue, New York, NY 10004',
                'education' => 'M.A. in English Literature, Yale University',
                'experience' => '12 years',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'TC004',
                'first_name' => 'James',
                'last_name' => 'Taylor',
                'email' => 'james.t@school.edu',
                'phone' => '+1 234-567-9003',
                'subject' => 'History',
                'status' => 'Active',
                'join_date' => '2018-09-05',
                'date_of_birth' => '1975-12-10',
                'address' => '654 Professor Road, New York, NY 10005',
                'education' => 'Ph.D. in History, Columbia University',
                'experience' => '20 years',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'TC005',
                'first_name' => 'Lisa',
                'last_name' => 'Chen',
                'email' => 'lisa.c@school.edu',
                'phone' => '+1 234-567-9004',
                'subject' => 'Computer Science',
                'status' => 'Active',
                'join_date' => '2022-01-10',
                'date_of_birth' => '1982-04-22',
                'address' => '987 Academic Way, New York, NY 10006',
                'education' => 'Ph.D. in Computer Science, Stanford University',
                'experience' => '10 years',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'TC006',
                'first_name' => 'Thomas',
                'last_name' => 'White',
                'email' => 'thomas.w@school.edu',
                'phone' => '+1 234-567-9005',
                'subject' => 'Physical Education',
                'status' => 'On Leave',
                'join_date' => '2017-06-15',
                'date_of_birth' => '1970-08-18',
                'address' => '147 Sports Boulevard, New York, NY 10007',
                'education' => 'M.Ed. in Physical Education, UCLA',
                'experience' => '25 years',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Seed courses
        DB::table('courses')->insert([
            [
                'id' => 'CRS001',
                'name' => 'Mathematics - Algebra',
                'code' => 'MATH-101',
                'grade' => 'Grade 10',
                'teacher_id' => 'TC001',
                'credits' => 3,
                'duration' => '90 min',
                'schedule' => 'Mon, Wed, Fri - 9:00 AM',
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'CRS002',
                'name' => 'Science - Physics',
                'code' => 'SCI-201',
                'grade' => 'Grade 11',
                'teacher_id' => 'TC002',
                'credits' => 4,
                'duration' => '90 min',
                'schedule' => 'Tue, Thu - 10:30 AM',
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'CRS003',
                'name' => 'English Literature',
                'code' => 'ENG-101',
                'grade' => 'Grade 9',
                'teacher_id' => 'TC003',
                'credits' => 3,
                'duration' => '60 min',
                'schedule' => 'Mon, Wed, Fri - 11:00 AM',
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'CRS004',
                'name' => 'World History',
                'code' => 'HIS-201',
                'grade' => 'Grade 12',
                'teacher_id' => 'TC004',
                'credits' => 3,
                'duration' => '90 min',
                'schedule' => 'Tue, Thu - 2:00 PM',
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'CRS005',
                'name' => 'Computer Science',
                'code' => 'CS-301',
                'grade' => 'Grade 10',
                'teacher_id' => 'TC005',
                'credits' => 4,
                'duration' => '120 min',
                'schedule' => 'Mon, Wed - 1:00 PM',
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'CRS006',
                'name' => 'Physical Education',
                'code' => 'PE-101',
                'grade' => 'Grade 11',
                'teacher_id' => 'TC006',
                'credits' => 2,
                'duration' => '60 min',
                'schedule' => 'Tue, Thu, Fri - 3:00 PM',
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Seed exams
        DB::table('exams')->insert([
            [
                'id' => 'EXM001',
                'title' => 'Midterm Exam - Mathematics',
                'course_id' => 'CRS001',
                'grade' => 'Grade 10',
                'exam_date' => '2024-02-15',
                'exam_time' => '09:00:00',
                'duration' => '2 hours',
                'type' => 'Midterm',
                'status' => 'Scheduled',
                'max_score' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'EXM002',
                'title' => 'Final Exam - Science',
                'course_id' => 'CRS002',
                'grade' => 'Grade 11',
                'exam_date' => '2024-03-20',
                'exam_time' => '10:00:00',
                'duration' => '2 hours',
                'type' => 'Final',
                'status' => 'Scheduled',
                'max_score' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'EXM003',
                'title' => 'Quiz - English Literature',
                'course_id' => 'CRS003',
                'grade' => 'Grade 9',
                'exam_date' => '2024-01-25',
                'exam_time' => '11:00:00',
                'duration' => '30 min',
                'type' => 'Quiz',
                'status' => 'Completed',
                'max_score' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'EXM004',
                'title' => 'Unit Test - World History',
                'course_id' => 'CRS004',
                'grade' => 'Grade 12',
                'exam_date' => '2024-02-10',
                'exam_time' => '14:00:00',
                'duration' => '1.5 hours',
                'type' => 'Unit Test',
                'status' => 'Completed',
                'max_score' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'EXM005',
                'title' => 'Practical Exam - Computer Science',
                'course_id' => 'CRS005',
                'grade' => 'Grade 10',
                'exam_date' => '2024-02-28',
                'exam_time' => '13:00:00',
                'duration' => '2 hours',
                'type' => 'Practical',
                'status' => 'Scheduled',
                'max_score' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'EXM006',
                'title' => 'Assessment - Physical Education',
                'course_id' => 'CRS006',
                'grade' => 'Grade 11',
                'exam_date' => '2024-01-30',
                'exam_time' => '15:00:00',
                'duration' => '1 hour',
                'type' => 'Assessment',
                'status' => 'In Progress',
                'max_score' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Seed payments
        DB::table('payments')->insert([
            [
                'id' => 'PAY001',
                'student_id' => 'ST001',
                'amount' => 1250.00,
                'type' => 'Tuition Fee',
                'method' => 'Credit Card',
                'payment_date' => '2024-01-15',
                'status' => 'Paid',
                'transaction_id' => 'TXN-2024-001234',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'PAY002',
                'student_id' => 'ST002',
                'amount' => 1250.00,
                'type' => 'Tuition Fee',
                'method' => 'Bank Transfer',
                'payment_date' => '2024-01-14',
                'status' => 'Paid',
                'transaction_id' => 'TXN-2024-001235',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'PAY003',
                'student_id' => 'ST003',
                'amount' => 500.00,
                'type' => 'Library Fee',
                'method' => 'Cash',
                'payment_date' => '2024-01-13',
                'status' => 'Paid',
                'transaction_id' => 'TXN-2024-001236',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'PAY004',
                'student_id' => 'ST004',
                'amount' => 1250.00,
                'type' => 'Tuition Fee',
                'method' => 'Credit Card',
                'payment_date' => '2024-01-12',
                'status' => 'Pending',
                'transaction_id' => 'TXN-2024-001237',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'PAY005',
                'student_id' => 'ST005',
                'amount' => 300.00,
                'type' => 'Exam Fee',
                'method' => 'Online Payment',
                'payment_date' => '2024-01-11',
                'status' => 'Paid',
                'transaction_id' => 'TXN-2024-001238',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'PAY006',
                'student_id' => 'ST006',
                'amount' => 1250.00,
                'type' => 'Tuition Fee',
                'method' => 'Bank Transfer',
                'payment_date' => '2024-01-10',
                'status' => 'Failed',
                'transaction_id' => 'TXN-2024-001239',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Seed attendance
        DB::table('attendance')->insert([
            [
                'id' => 'ATT001',
                'class_name' => 'Grade 10 - Mathematics',
                'teacher_id' => 'TC001',
                'attendance_date' => '2024-01-15',
                'total_students' => 30,
                'present' => 28,
                'absent' => 2,
                'late' => 0,
                'status' => 'Completed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'ATT002',
                'class_name' => 'Grade 11 - Science',
                'teacher_id' => 'TC002',
                'attendance_date' => '2024-01-15',
                'total_students' => 25,
                'present' => 24,
                'absent' => 1,
                'late' => 0,
                'status' => 'Completed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'ATT003',
                'class_name' => 'Grade 9 - English',
                'teacher_id' => 'TC003',
                'attendance_date' => '2024-01-15',
                'total_students' => 28,
                'present' => 27,
                'absent' => 0,
                'late' => 1,
                'status' => 'Completed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'ATT004',
                'class_name' => 'Grade 12 - History',
                'teacher_id' => 'TC004',
                'attendance_date' => '2024-01-14',
                'total_students' => 22,
                'present' => 20,
                'absent' => 2,
                'late' => 0,
                'status' => 'Completed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'ATT005',
                'class_name' => 'Grade 10 - Computer Science',
                'teacher_id' => 'TC005',
                'attendance_date' => '2024-01-14',
                'total_students' => 30,
                'present' => 29,
                'absent' => 1,
                'late' => 0,
                'status' => 'Completed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'ATT006',
                'class_name' => 'Grade 11 - Physical Education',
                'teacher_id' => 'TC006',
                'attendance_date' => '2024-01-16',
                'total_students' => 25,
                'present' => 0,
                'absent' => 0,
                'late' => 0,
                'status' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        $this->command->info('Initial data seeded successfully');
    }
}

